### ISSUE TITLE
Unable to use it

### ISSUE THREAD

**Issue by gloubix** [MicahParks/wigole#1]
Hi,

Trying to launch an example but this does not make anything apart saying that it has found the modules and then stops. No error. Not trying to even read the creds.json.
How to proceed ?

Thx

**Comment by MicahParks** [comment]
I can look more into this later, but it looks like the API has been updated to v3. This wrapper was for v2.
See the link in the `README.md`.

**Comment by MicahParks** [comment]
It looks like some examples are still working with a valid `creds.json` file.

Here's what I just got for `networkSearch.go`
```bash
$ go run examples/networkSearch.go 
974
```

Is it possible you were using `go build` instead of `go run`?

Sorry to disappoint, but since WiGLE has moved to v3 of their API, I'm going to archive this project and put a notice in the `README.md`. I think you _might_ still be able to use this repository for interacting with v2 of their API, but I'm not sure if that is deployed or if their v3 API or just partially backwards-compatible.

If you need to use v3 of their API for something serious or something that has business value, I would recommend generating a client from their Swagger 2.0 (OpenAPI 2) specification located at `https://api.wigle.net/swagger.json`.

My favorite way to do this in Go is using this project:
https://github.com/go-swagger/go-swagger

HOWEVER, I remember trying to do that for v2 of their API and it didn't work due to a server side implementation that wasn't 100% compatible with the specification published, hence, this project.
